### ISSUE TITLE
Restraint Points are still bugged, can go negative

### ISSUE THREAD

**Issue by PoisDesu** [PoisDesu/Didnapper-2#10]
**Bug description**
Restraint Points be no working

**To reproduce**
* Any item that can reduce RP? 

**Screenshots/Video**
![unknown 1](https://user-images.githubusercontent.com/96031678/145942682-6900b577-c605-4de7-9786-3be6aaf43515.png)
Kaie has -1 restraint point

**Comment by beneficialbadger** [comment]
Fixed.
