### ISSUE TITLE
Can unlock chests while tied

### ISSUE THREAD

**Issue by defcab** [PoisDesu/Didnapper-2#12]
**Bug description**
It is possible to unlock chests while tied during the hopping sequence in chapter 7.

**To reproduce**
* Go to Chapter 7 / Confrontation on a cliff.
* Escape the connection tie to enter hopping mode.
* Go into the sleeping room directly above and open the chest.

**Expected behavior**
The chest should not open.
What actually happens is the game plays the buzz sound and skips the mini-game, but then gives you the item anyway.

**Screenshots/Video**
![chest](https://user-images.githubusercontent.com/17232766/145971758-278a4579-6d83-4621-86b1-ea4fda23c953.png)

**Environment (please complete the following information):**
 - OS: Windows
-  OS Version: 10
-  Game version and platform: 1.0.1 Itch

**Input method**
Controller

**Save file**
[file50.zip](https://github.com/PoisDesu/Didnapper-2/files/7710383/file50.zip)

**Additional context**
The cause appears to be the mini-game success variable not being initialized and/or not being set when canceled.

**Comment by Kendrian** [comment]
Fixed
