### ISSUE TITLE
Attempting to carry an enemy when Seles or Aden is not the lead character throws an error

### ISSUE THREAD

**Issue by defcab** [PoisDesu/Didnapper-2#13]
**Bug description**
In Etznanl, if Seles or Aden is not the lead character when you attempt to carry an enemy, it throws the error:
"Failed to load: image/characters/KaieCasualCarry.png" (or EileenCasualCarry.png)

**To reproduce**
* In the Etznanl port when controlling Aden's party, switch the party order to put Eileen or Kaie in front.
* Attempt to carry a captured enemy.

**Expected behavior**
The character should carry the enemy,

**Environment (please complete the following information):**
 - OS: Windows
-  OS Version: 10
-  Game version and platform: 1.0.1 Itch

**Input method**
Keyboard

**Save file**
[file50.zip](https://github.com/PoisDesu/Didnapper-2/files/7710563/file50.zip)

**Additional context**
Probably need to either lock Aden to the front or add carrying sprites for the other characters.

**Comment by Kendrian** [comment]
Fixed with placeholder graphics
