### ISSUE TITLE
1.0.2 Save issue: "Unexpected token o in JSON at position 1" and/or save disabled.

### ISSUE THREAD

**Issue by fabbemannen** [PoisDesu/Didnapper-2#16]
**Bug description**
When saving, possibly only when writing over an existing file, the game either:
1. Saves the game, only to then get stuck due to "Unexpected token o in JSON at position 1". Save completes and can be loaded from, but game has to be restarted.
2. Fails to save (can only hear a bzzt sound like if it was disabled). Can sometimes fix itself just by trying again. Sometimes the JSON error occurs when doing this and the game has to be restarted without being able to save your progress.
3. Saves normally, no issues.

Once, the entire save menu could not load (stuck on Loading...) and the game had to be restarted. Possibly unrelated.
All these issues occurred in ch.12 and 13 after I transitioned from 1.0.1 to 1.0.2.

**To reproduce**
* Open save menu
* Choose an existing save file (possibly)
* Save

Unfortunately I can't consistently reproduce the issues.

**Expected behavior**
The game overwrites the selected file (with the normal "select-sound") and can continue to be played without having to restart the game and/or lose progress.

**Screenshots/Video**
JSON error
![Example 1](https://user-images.githubusercontent.com/6573347/146280168-86ed6fd0-cf93-4bee-a2f7-b8b504d80eec.png)

Example of a file that crashed, but still saved and could be loaded
![After loading a save that crashed](https://user-images.githubusercontent.com/6573347/146280248-26dacf5a-fcbc-42e9-a742-ffb20b3c974f.png)

**Environment (please complete the following information):**
 - OS: Windows 10
-  OS Version: 19043.1348
-  Game version and platform: 1.0.2 itch (saves were created on 1.0.1)

**Error logs**
[crashlogs.txt](https://github.com/PoisDesu/Didnapper-2/files/7723451/crashlogs.txt)
[logs.txt](https://github.com/PoisDesu/Didnapper-2/files/7723453/logs.txt)

**Save file**
[save.zip](https://github.com/PoisDesu/Didnapper-2/files/7723455/save.zip)
Uploaded the entire save folder. The pictures were taken on save 5 and 4, but the first five all had the issue.

**Additional context**
I haven't tried quicksaving since it wrote over the wrong savefile earlier (unrelated issue I assume) and I'd rather not risk testing that right now.
I've had zero issues with saves otherwise before updating to 1.0.2 (this includes official release and beta versions).

**Comment by PoisDesu** [comment]
Have you tried doing a clean re-installation of the game and moving your save folder over to the clean installation?

**Comment by fabbemannen** [comment]
Yes, I actually tried both overwriting the old installation folder and making a clean install to see if there was a difference, but there wasn't.

That said, I kept playing today and the problem got better near the end of ch.13 and never occurred again in ch.14 and forward. Wish I could've gotten some proper reproduction steps in case it happens to someone else, but at least it doesn't seem to be a problem for me anymore.

If it was a problem with the save file update from 1.0.1 to 1.0.2, then maybe it fixes itself when it gets the correct info. If it was just my computer, well, who knows then?

**Comment by beneficialbadger** [comment]
Hypothesis: some event causes a plugin to put something in $gameSystem that the save system can't handle, so it either fails or removes/fixes the problematic part and saves successfully. Therefore, this bug can't be reproduced from a save after it happened. We'd need to find one before and see what is it trying to save and failing.

(similar things happened back when I broke saves in the beta once)

**Comment by PoisDesu** [comment]
Is there anything the save system can't handle? Last I looked it seemed able to stringify virtually anything

**Comment by beneficialbadger** [comment]
Yes. I used to store my entire Interaction objects and it was fine until I switched to layers and added WindowLayer with Sprites - Bitmaps to my objects. Not sure which part exactly was the culprit, because I scrapped all of that once the issue with saves occurred.

**Comment by PoisDesu** [comment]
Ah, I'd wager bitmaps might have been the culprit in that case, will get around to test that tomorrow

**Comment by PoisDesu** [comment]
Sure enough, a bitmap in $gameSystem does break things, but seemingly in a different way. Probably will need to make the save system handle this kind of stuff gracefully

**Comment by beneficialbadger** [comment]
I found it inconsistent in how it broke things. A highlight was a seemingly successful save which then refused to load because Game_Screen was in $gameSystem.

Anyway, wouldn't it be simpler to just not save bitmaps?

**Comment by PoisDesu** [comment]
It would be, however I'm not aware of any part of the code that does that, none of the plugins are supposed to put a bitmap in $gameSystem
