### ISSUE TITLE
Random enemy scope for elemental skills shows error message

### ISSUE THREAD

**Issue by Kendrian** [PoisDesu/Didnapper-2#19]
**Bug description**
When using an elemental skill that targets multiple random enemies (for instance the Scope called 2 Random Enemies), the game may not be able to find the elementRate of the enemy, displaying an error message in the damage text (see screenshot)

**To reproduce**
1. Use an elemental skill with multiple random targets (for example Aden's Quck Pellets)
2. Fight multiple enemies at a time who have weakness or resistance to the element, so the target can change between the hits of the skill 
3. Profit

**Expected behavior**
It shows the element rate of the enemy currently taking damage

**Screenshots/Video**
https://cdn.discordapp.com/attachments/557299091680395275/921708928235085844/unknown.png

**Environment (please complete the following information):**
 - OS: Any
-  OS Version: Any
-  Game version and platform: v1.0.2 probably, though was reported from v1.0.1

**Input method**
Irrelevant

**Error logs**
Haven't received one

**Save file**
None

**Additional context**
Probably has to do with the part of the code reading the enemy's element rate being confused when the target changes mid-skill, not knowing which enemy to read the rate from or something. Either that or the random enemy scope isn't accounted for.

**Comment by beneficialbadger** [comment]
fixed
