### ISSUE TITLE
1.0.2 Winning the Zhara encounter in Chapter 1 softlocks the game

### ISSUE THREAD

**Issue by ThatDino** [PoisDesu/Didnapper-2#22]
**Bug description**
Upon returning to the first Zhara encounter and then managing to defeat her instead of her subduing the player, the cutscene plays out as if Zhara had won, after which the game softlocks on a black screen after the save option.

**To reproduce**
* Be leveled high enough
* Know a stunning move
* Go back to the Zhara encounter via Story Crystal
* Fight her and manage to stun and subdue her

**Expected behavior**
The game softlocks on a black screen after the save option, opening the menu is still possible

**Screenshots/Video**
A black screen, I don't think we'll need a screenshot.

**Environment (please complete the following information):**
 - OS: Windows
-  OS Version: 10
-  Game version and platform: 1.0.2 (Itch.io)

**Input method**
Keyboard/Mouse

**Error logs**
Attach the `crashlogs.txt` and `logs.txt` files if they exist.
They can be found in the game's folder, within `logs`, at the same level as the save folder. (On Windows, that is under the `www` folder)

**Save file**
Attach the save file you experienced the bug in, it can be found in the game's folder, within `save`. (On Windows, that is under the `www` folder).
Either zip the file and send it here, or upload it somewhere else and put the link here

**Additional context**
This is one of the few fights which should not be won, will try some other places next (if there are any, can't remember).

**Comment by PoisDesu** [comment]
You are not supposed to win that fight.

**Comment by ThatDino** [comment]
I know that, but a softlock is hardly the way to go in that situation. If the possibility is given through Story Crystal backtracking, it feels hardly appropriate. It's not like the player is cheating.

**Comment by ThatDino** [comment]
> You are not supposed to win that fight.

I know that, but a softlock is hardly the way to go in that situation. If the possibility is given through Story Crystal backtracking, it feels hardly appropriate. It's not like the player is cheating.

**Comment by Kendrian** [comment]
The battle had nothing to do with the softlock. It had to do with a remnant from the chapter 13 scene in that room preventing the chapter 1 scene from triggering, whether or not the battle was won. It's been fixed on our end now. Thanks for reporting it regardless, as knowing you were high level (late-game) was a clue to why we couldn't reproduce the bug before :)

**Comment by ThatDino** [comment]
Weird way round the bend, but good to know. Thank you all for your work! ^v^
