### ISSUE TITLE
The skill「Judgement Hammer」has a chance to keep the game freeze in the battle.

### ISSUE THREAD

**Issue by shoutakumin** [PoisDesu/Didnapper-2#24]
**Bug description**
If there are more than six female enemies in a battle and all of them are weakened, using the skill (Judgement Hammer) will has a chance to knock out female enemies instead of subduing them. Most importantly, when you use this skill to knock out female enemies, if there are other enemies alive (including captured enemies), the game will freezes in battle. All skills show that [No enemy available],  and even the surrender cannot be used. All you can do is press the F5 LoL.

**To reproduce**
Updated on December 22, 2021
1：Battle with two or more female enemies. (Greywind-Manor garden is a good choice.)
2：Use the skill (Judgement Hammer) when all female enemies are weakened.
3：To trigger this bug, you just need to speed up the game by holding down the left mouse button or space bar while using the skill. If you release the button while the skill is in progress, the game will freeze. If you hold down the mouse or space bar all the time,  all enemies will be knocked out at the end of the battle.

**Expected behavior**
All female enemies should be subdued at the end of the battle.

**Screenshots/Video**
![1](https://user-images.githubusercontent.com/96416513/146760386-e7945f4f-21eb-4602-a85a-add4440cc57b.png)
![2](https://user-images.githubusercontent.com/96416513/146760430-afb959f8-252d-41ac-91e8-6e2752e680dc.png)
![3](https://user-images.githubusercontent.com/96416513/146760479-11eed1b4-6b8e-465e-851e-1f230521475e.png)

**Environment (please complete the following information):**
 - OS:  Windows
-  OS Version:  Windows 10 Pro 20H2
-  Game version and platform: 1.0.2 Steam

**Input method**
mouse and keyboard

**Error logs**
no exist

**Save file**
Sorry, I can't find it...

**Additional context**
That's all.

**Comment by shoutakumin** [comment]
Additional context：
I think I found the real cause of this bug. This bug will trigger when battling with more than two female enemies. To trigger this bug, you only need to speed up the game by holding down the left mouse button or space bar while using the skill. If you release the button while the skill is in progress, the game will freeze. If you hold down the mouse or space all the time, the battle will end with all enemies knocked out.

**Comment by shoutakumin** [comment]
Can't reproduce with the updated method？

**Comment by PoisDesu** [comment]
I personally cannot reproduce it seemingly because my computer is too fast, but others can, and apparently, it's related to the "post-battle wait" option. In your game's options, is "post-battle wait" on?

**Comment by shoutakumin** [comment]
Oh, I found that the bug only appeared when I turned it on.

**Comment by shoutakumin** [comment]
But I also found that this bug would not appear if the game was not speeded up after turn it on.
