### ISSUE TITLE
Gallery Screen #10 and Game Over Screen Not Displaying

### ISSUE THREAD

**Issue by calboi91** [PoisDesu/Didnapper-2#3]
**Bug description**
Game over screen in chapter 2 after defeating the robot does not display properly (black screen). It unlocks gallery screen 10, which also does not display properly (shows a blurred screen of the main menu). 

**To reproduce**
* Be at chapter 2 after defeating the robot
* Surrender and get locked up
* Give up to trigger the game over screen

**Expected behavior**
Expected to see the proper screen. In the gallery, the preview thumbnail for 10 is displaying properly. 

**Screenshots/Video**
If applicable, add screenshots to help explain your problem, or a video if more relevant.

**Environment (please complete the following information):**
 - OS: Windows
-  OS Version: 10
-  Game version: 1.0.1

**Input method**
If relevant, note the input method you were using (mouse, keyboard or controller). If a controller, specify what kind of controller (e.g. Xbox One controller)
Keyboard/mouse and ps4 controller

**Error logs**
Attach the `crashlogs.txt` and `logs.txt` files if they exist.
They can be found in the game's folder, within `logs`, at the same level as the save folder. (On Windows, that is under the `www` folder)
[logs.txt](https://github.com/PoisDesu/Didnapper-2/files/7702047/logs.txt)

**Comment by calboi91** [comment]
Ok, problem went away after reinstalling. So probably some corrupted file.

**Comment by PoisDesu** [comment]
For the record, with what software did you unzip the game?

**Comment by calboi91** [comment]
I used the itch.io game manager to download and install it.
