### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by Tiatitan** [PoisDesu/Didnapper-2#35]
Forgive my pickiness, my parents were both English teachers and I noticed a few typos.

Screenshot 1: The comma after bloodline should have a space

![Screenshot (737)](https://user-images.githubusercontent.com/96554996/147639382-cbf8a56a-10e0-4169-be73-879b0cc10850.png)

Screenshot 2: "You should hope I [do not] need to"

![Screenshot (742)](https://user-images.githubusercontent.com/96554996/147639453-2102b4b6-4714-444f-9507-be078dbce032.png)
 
Screenshot 3: I took the screenshot too late! But the line before this one, Liliana's retainer says she will pass a message "onto" Liliana. I believe it should be to pass a message "on to" Liliana.

![Screenshot (743)](https://user-images.githubusercontent.com/96554996/147639590-8afcae26-1910-48eb-821b-75149c8bd6ff.png)

**Comment by PoisDesu** [comment]
Thanks for the report! I'll note that the third one won't be fixed, however, as "onto" is perfectly valid

**Comment by Tiatitan** [comment]
Thanks for the reply. And, forgive my wording. I was trying to being polite, but in saying "I believe it should be..." I failed to express that it is actually grammatically incorrect. "Onto" is a preposition implying that an object is moving on top of something. When used, "onto" can be replaced with the preposition "on".

"On to", however, implies the transfer of something, but not necessarily a physical movement on top of something. The information is not be moved on top of Liliana. Rather, it is being transferred on to Liliana.

Again, I'm self conscious being nitpicky given my family is full of literature nerds. But, it is a grammatical error I wanted to point out ><

https://www.sjsu.edu/writingcenter/docs/handouts/Onto%20vs.%20On%20To.pdf
