### ISSUE TITLE
MacOS Permissions issue at Startup. Saving disabled.

### ISSUE THREAD

**Issue by spooning2forking** [PoisDesu/Didnapper-2#37]
**Bug description**
The following error messages appear upon startup (pictured). When trying to run the game, I am unable to save. This seems to be a permissions issue but I can't figure it out.

**Screenshots/Video**
![Screen Shot 2021-12-30 at 8 01 49 PM](https://user-images.githubusercontent.com/96899262/147802723-9b7e4b11-0c0e-4b94-85f6-52bcd0835049.png)
![Screen Shot 2021-12-30 at 8 06 02 PM](https://user-images.githubusercontent.com/96899262/147802725-dd451a9e-5f64-4994-9736-08d46d773593.png)

**Environment (please complete the following information):**
 - OS: MacOS 
-  OS Version: Catalina 10.15.7
-  Game version and platform: itch.io Didnapper2 v1.0.2

**Comment by PoisDesu** [comment]
Some macOS folders have restricted permissions, try to move the game to another folder, or even create a new one. In the event that also fails, moving the game executable (not the rest of the game) into the "Applications" folder might solve it.

**Comment by spooning2forking** [comment]
Thanks! I haven't figured it out yet but I'll continue tinkering in that
direction.
