### ISSUE TITLE
PS4 Left Joystick Not Fully Working in Windows 10

### ISSUE THREAD

**Issue by calboi91** [PoisDesu/Didnapper-2#4]
**Bug description**
When using a PS4 controller connected via Bluetooth in Windows 10, the left joystick can only move the character up or down, not left or right. 

**To reproduce**
* Connect PS4 controller via Bluetooth
* Move character left or right using left joystick

**Expected behavior**
Expect the character to move left or right. 

**Screenshots/Video**
If applicable, add screenshots to help explain your problem, or a video if more relevant.

**Environment (please complete the following information):**
 - OS: Windows
-  OS Version: 10
-  Game version: 1.0.1

**Input method**
If relevant, note the input method you were using (mouse, keyboard or controller). If a controller, specify what kind of controller (e.g. Xbox One controller)
PS4 Controller

**Error logs**
Attach the `crashlogs.txt` and `logs.txt` files if they exist.
They can be found in the game's folder, within `logs`, at the same level as the save folder. (On Windows, that is under the `www` folder)
[logs.txt](https://github.com/PoisDesu/Didnapper-2/files/7702064/logs.txt)

**Comment by PoisDesu** [comment]
Getting to this really late because I do not have a PS4 controller, are you using DS4Windows? (https://github.com/Ryochan7/DS4Windows)

**Comment by calboi91** [comment]
No I did not use DS4Windows, but just the controller's input directly.

**Comment by PoisDesu** [comment]
Right, you might want to use it, it should fix all issues related to the Bluetooth connection. There isn't much we can do on our end about it, this is an issue within the framework itself, or perhaps even within windows, none of which are things we can touch.
