### ISSUE TITLE
Two Female Enemies Subdue Failure

### ISSUE THREAD

**Issue by Whatisavalible** [PoisDesu/Didnapper-2#41]
**Bug description**
When I am fighting two female enemies (possibly more, I have not tested more than 2 enemies.) I am unable to normally subdue the rightmost enemy until I have weakened the leftmost enemy. If I attempt to, the first click leads to a brief flash of the targeted sprite but no effect. Further clicks generate a beeping noise.

The bug does not seem to affect single female enemies; I defeated the boss and Subdued her as normal.

There is an oddity where, when I then click on the leftmost enemy (who is not weakened) the Subdue animation played on the Weakened enemy and they are subdued as normal.

**To reproduce**
* Challenge 2 female enemies
* Weaken the rightmost enemy
* Click on Subdue
* Click on the enemy
* Subdue does not take effect
* Further clicks lead to beeping noise
* Click on un-weakened enemy leads to Subdue triggering on originally-targeted enemy.

**Expected behavior**
I expect to be able to subdue the rightmost female enemy without having to weaken the leftmost female enemy, and without having to click on the leftmost enemy.

**Screenshots/Video**
N.A.

**Environment (please complete the following information):**
 - OS: [Mac]
-  OS Version: [e.g. macOS 10.14.6 Mojave]
-  Game version and platform: [e.g. 1.0.3 Steam]

**Input method**
Tracpad mouse and keyboard

**Error logs**
N.A.

**Save file**
Unavailable: I can't find where the save is stored.

**Additional context**
A similar issue that I think might be related popped up during testing: when my rightmost party member (Liliana) got Subdued and I attempted to use the Rescue command, I got the same issue (Click, brief flash of sprite, then additional clicks lead to a beeping noise).

**Comment by PoisDesu** [comment]
Noted. You can use the keyboard as an alternative for now, it should work as expected
