### ISSUE TITLE
Typos + Chelsea missing a layer in boss fight dialogue?

### ISSUE THREAD

**Issue by Tiatitan** [PoisDesu/Didnapper-2#42]
1.
-Nothing game breaking by any means. The phrase in this case would be "I couldn't care less." As it stands, this dialogue implies Byron _does_ care - although his actions show otherwise. 
![Screenshot (745)](https://user-images.githubusercontent.com/96554996/147869449-6ff22ec4-979a-4e0e-a062-e2454264cf94.png)

2.
-Pretty sure this is Elize's dialogue given the context and that Elize's animation has the mouth flaps. However, it is ascribed to a shocked Zhara.
![Screenshot (746)](https://user-images.githubusercontent.com/96554996/147869456-64ec880f-5e53-4950-8956-f6edd82fac1b.png)

3.
-I don't have a screenshot for this one, but at times the music in the game would stop until I loaded a new area, entered a building, or started plot-dialogue. I particularly noticed it in the forest before the fight with King Byron. The music would randomly cut out, but the battle music played when I fought creatures. The forest soundtrack would still be silent after a battle, but it came back if I either  went to the lodge by the shore or started the dialogue with Byron.

4.
-Lastly:
Sometimes during fights, characters would gain about 200-300 EXP. Only to fight the same enemies again and get 0 EXP. And those same enemies might give another couple hundred EXP on a follow-up fight. At first I thought the game was trying to get me to catch up, so to speak, by giving me so much EXP. I was then confused when grinding the same enemies gave me 0, as if it was a sign that I had maxed out my level. I don't know if this was a glitch, or if EXP is simply given randomly.

**Comment by Kendrian** [comment]
Fixed Zhara and Elize dialogue nametag switch

**Comment by Tiatitan** [comment]
Thanks for the comment, and wow I just realized I forgot to change the title of this thread. I thought Chelsea was missing a layer and later realized she wasn't, but I forgot to change the header ><
