### ISSUE TITLE
Wallpaper pictures cropped

### ISSUE THREAD

**Issue by MasterKi11er** [PoisDesu/Didnapper-2#5]
**Bug description**
I have noticed in the gallery, pictures 7 and 11 in wallpaper mode shows the cropped version of the picture. There may be more but I have only unlocked until pic 12.

**To reproduce**
1) Go to gallery
2) Click on pic 7/pic 12

**Expected behavior**
A full view of the picture should be expected in wallpaper mode.

**Screenshots/Video**
![WallpaperBug](https://user-images.githubusercontent.com/96066514/145836174-96148e2a-826a-463a-9906-1c6f754655af.png)

**Environment:**
 - OS: Windows 10
-  OS Version: 
-  Game version: 1.0.1

**Comment by AbruptLee** [comment]
Still issue as of 1.0.3; Pics effected are: Pic 7 (Aden), Pic 11 (Eileen), and Pic 13 (Lili, Dariana, and Alyssa). Pic 12 of chair-tied Liliana is fine.
