### ISSUE TITLE
Collision Testing for the Stromm Bandit Camp

### ISSUE THREAD

**Issue by Pinn1** [PoisDesu/Didnapper-2#59]
**Bug description**
A collection of screenshots highlighting map oddities in the Collision Testing for the Stromm Bandit Camp that may warrant inspection by the development team.

**To reproduce**
Walk to the highlighted tiles and follow the arrows or attempt to walk into them.

**Expected behavior**
Dependent on the scenario.
The question marks around the rope bundles signifies that I'm unsure if the player should be able to walk over them or not. Similar to logs, rope bundles are inconsistent in this. 
Cracks that maybe should be walkable. Jars that shouldn't. etc.

**Screenshots/Video**
If applicable, add screenshots to help explain your problem, or a video if more relevant.
![Capture9 - Stromm Bandit Camp - Caves](https://user-images.githubusercontent.com/97575225/149687146-a76fc871-fa94-4bc4-8c26-62d492f644f4.PNG)
![Capture10](https://user-images.githubusercontent.com/97575225/149687171-5ab1f300-049d-4665-ac7f-d8f766b0e800.PNG)
![Capture11](https://user-images.githubusercontent.com/97575225/149687184-11a97ec8-7bcb-4872-8c78-02699884de6a.PNG)
![Capture12](https://user-images.githubusercontent.com/97575225/149687214-a4aaf262-a47c-45a2-a3a0-0dab54588f0a.PNG)
![Capture13](https://user-images.githubusercontent.com/97575225/149687225-03f44d8d-d494-461d-9a01-ace8efb05caa.PNG)
![Capture14](https://user-images.githubusercontent.com/97575225/149687243-1af1c3c4-4c97-45b9-be9e-009c47fc4566.PNG)
![Capture15](https://user-images.githubusercontent.com/97575225/149687257-bd4187ed-62cc-41f4-ab81-e656c1126d58.PNG)

**Environment (please complete the following information):**
-  OS & Version: [e.g. macOS 10.5 Catalina] Windows 10
-  Game version and platform: [e.g. 1.0.1 Steam] Itch 1.0.3

**Input method**
If relevant, note the input method you were using (mouse, keyboard or controller). If a controller, specify what kind of controller (e.g. Xbox One controller)

**Error logs**
Attach the `crashlogs.txt` and `logs.txt` files if they exist. ([Where are the log files?](https://github.com/PoisDesu/Didnapper-2/wiki#where-are-the-log-files))

**Save file**
Attach the save file you experienced the bug in ([Where are the save files?](https://github.com/PoisDesu/Didnapper-2/wiki#where-are-the-save-files))
Either zip the file and send it here, or upload it somewhere else and put the link here

**Additional context**

**Comment by Kendrian** [comment]
Glad to have you back in action :P

**Comment by Pinn1** [comment]
Haha thanks, Ken! :)
