### ISSUE TITLE
cannot read property 'parentIDs' of null

### ISSUE THREAD

**Issue by MacHaggoose** [PoisDesu/Didnapper-2#68]
**Bug description**
trying to load a save produces a screen that says "cannot read property 'parentIDs' of null"

**To reproduce**
* load a save

**Expected behavior**
the save would load and i can play the game

**Screenshots/Video**
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/28915338/175861898-dac88efd-2cf3-47c8-9c01-f385cadcf727.png">

**Environment (please complete the following information):**
-  OS & Version: [e.g. macOS 12.4 monterey]
-  Game version and platform: 1.0.5demo itch

**Input method**
keyboard

**Error logs**
Attach the `crashlogs.txt` and `logs.txt` files if they exist. ([Where are the log files?](https://github.com/PoisDesu/Didnapper-2/wiki#where-are-the-log-files))
[logs.txt](https://github.com/PoisDesu/Didnapper-2/files/8988758/logs.txt)
[crashlogs.txt](https://github.com/PoisDesu/Didnapper-2/files/8988760/crashlogs.txt)

**Save file**
Attach the save file you experienced the bug in ([Where are the save files?](https://github.com/PoisDesu/Didnapper-2/wiki#where-are-the-save-files))
Either zip the file and send it here, or upload it somewhere else and put the link here
[file28.rpgsave.zip](https://github.com/PoisDesu/Didnapper-2/files/8988740/file28.rpgsave.zip)

**Additional context**
problem first started after one successful load, then appeared when changing screens, after that, no save file would load. tried updating the game and restarting.

**Comment by PoisDesu** [comment]
Hey there, you wrote down that your game version is the 1.0.5 demo, but your save file seems to be from the full 1.0.5 game, can you confirm?

**Comment by MacHaggoose** [comment]
yeah, itch had been bugging me for a while to update the game, and i finally did it after this issue started. i wasn't sure what to make of it when the file said demo on it after it finished. i just uninstalled and re-installed the game and it looks like that got rid of the demo version filename, but also cleared all my save files so maybe this is all moot now

**Comment by Kendrian** [comment]
Ah, I presume that when you updated, it gave you the choice between downloading the latest full version or the latest demo, and you selected the latest demo. The save file you attached here should work fine on a fresh installation of the full version, though. Just start a new game and make a new save, then rename and replace the file you shared here with the new save you made.

**Comment by MacHaggoose** [comment]
yes, it all worked out. glad i took the time to attach it here. thanks.
