### ISSUE TITLE
Screen freeze at Pirate Den

### ISSUE THREAD

**Issue by PvtFreaky** [PoisDesu/Didnapper-2#7]
**Bug description**
At the end of the fight with Darianna and Alyssa (which is bloody hard), Lilianes guards come in and talk a bit. Whenever the 2 standard Royal guards come in the game freezes.

**To reproduce**
I've fought Darianna and Alyssa again and the same screen freeze happened at the exact same moment.

**Expected behavior**
I thought the guards would take away Darianna and Alyssa or something.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/96072011/145848484-78d98434-f391-4fca-ae43-698a73738417.png)

**Environment (please complete the following information):**
 - OS: [Windows]
-  OS Version: [10]
-  Game version: [e.g. 1.0.1]

**Input method**
Laptop keyboard

**Error logs**
No crashlog

**Additional context**

**Comment by PoisDesu** [comment]
Could you send the save file you're using?

**Comment by PvtFreaky** [comment]
I can't drag the file to here

**Comment by PoisDesu** [comment]
Oh right, you can either zip it or upload it somewhere else and send the link

**Comment by PvtFreaky** [comment]
Sorry I am terrible with computers, how do I do that? It says that I can't use 7zip on it

**Comment by PvtFreaky** [comment]
Do you have discord? I am Bordela there, maybe I can share it there?

**Comment by PvtFreaky** [comment]
There you go

I've tried it for a fourth time with full computer restart, and again same
bug


Thanks for the help

Op ma 13 dec. 2021 om 18:15 schreef Pwa ***@***.***>:

**Comment by PoisDesu** [comment]
[file25.zip](https://github.com/PoisDesu/Didnapper-2/files/7706081/file25.zip)

**Comment by PvtFreaky** [comment]
Should I use this file now?

**Comment by PoisDesu** [comment]
Reproduced similar scenario with fast skipping 

![image](https://user-images.githubusercontent.com/96031678/145882107-b768487f-e080-45e9-9579-41826b693e72.png)
