### ISSUE TITLE
Camaris , Off screen Hopping

### ISSUE THREAD

**Issue by FreelanceBoy** [PoisDesu/Didnapper-2#9]
**Bug description**
You can hop out of the scene at bottom left but you can also hop back in.
**To reproduce**
1. Go in the rest room after escape 
2. Hop through the closet bottom left and you can be hop back through the sand back near it.

**Expected behavior**
Please fix the passable object so I can't hop out again.
**Screenshots/Video**
![InkedBug report_LI](https://user-images.githubusercontent.com/96097754/145928055-eeb29f9b-99fa-4cb3-b994-d22577a609e0.jpg)

**Environment (please complete the following information):**
 - OS: Window 10
-  OS Version:
-  Game version: 1.01 

**Input method**
Keyboard
**Error logs**
None

**Comment by Kendrian** [comment]
Fixed in v1.0.2
